### ISSUE TITLE
Weird behavious in arc!userinfo

### ISSUE THREAD

**Issue by romangraef** [SkryptKiddie/Arc#4]
https://github.com/SkryptKiddie/Arc/blob/3e92fef3179a7b312de72dbfd2a771f25575208a/bot.py#L184
a) in embed titles mentions dont work
b) if a parameter to a `@bot.command` may be `None` you have to indicate that via: `user: discord.Member = None`

**Comment by SkryptKiddie** [comment]
I have fixed (a) and am working on a fix for (b), thank you for bringing these up!
